exports.quotes = [
	"If mommy's purse didn't belong in the microwave, why did it fit?",
	"I wet my arm pants.",
	"Grandma had hair like that when she went to sleep in her forever box!",
	"All my friends have birthdays this year!",
	"I'm bembarassed for you.",
	"My knob tastes funny. (thanks to Lee Johnson)",
	"Hi, Principal Skinner! Hi, Super Nintendo Chalmers.",
	"And I want a bike and a monkey and a friend for the monkey.",
	"Eww, Daddy, this tastes like Gramma!",
	"I bent my wookie.",
	"Lisa's bad dancing makes my feet sad.",
	"That's where I saw the Leprechaun. He tells me to burn things.",
	"Look Big Daddy, it's Regular Daddy.",
	"Look, Daddy, a whale egg!",
	"Daddy, I'm scared. Too scared to wet my pants.",
	"My cat's name is Mittens.",
	"This snowflake tastes like fish sticks.",
	"My parents won't let me use scissors.",
	"Slow down, Bart! My legs don't know how to be as long as yours.",
	"When I grow up I wanna be a Principal or a Caterpillar.",
	"Principal Skinner, I got carsick in your office.",
	"Dear Miss Hoover, you have Lyme disease. We miss you. Kevin is biting me. Come back soon. Here's a drawing of a spirokeet. Love Ralph",
	"Bushes are nice 'cause they don't have prickers. Unless they do. This one did. Ouch!",
	"I dress myself.",
	"This is my sandbox, I'm not allowed to go in the deep end.",
	"The doctor told me that BOTH my eyes were lazy! And that's why it was the best summer ever",
]